# Generated by Django 5.2.7 on 2026-02-04 12:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning_app', '0003_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Devoir', 'verbose_name_plural': 'Devoirs'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date'], 'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'verbose_name': 'Résultat de quiz', 'verbose_name_plural': 'Résultats de quiz'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Soumission', 'verbose_name_plural': 'Soumissions'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=20, verbose_name='Niveau de difficulté'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_weeks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (semaines)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frais (XOF)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du cours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to=settings.AUTH_USER_MODEL, verbose_name='Formateur'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('completed', 'Terminé'), ('dropped', 'Abandonné')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (XOF)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Carte de crédit'), ('debit_card', 'Carte de débit'), ('upi', 'UPI'), ('net_banking', 'Virement bancaire'), ('cash', 'Espèces')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Étudiant'), ('trainer', 'Formateur'), ('manager', 'Gestionnaire')], max_length=10),
        ),
    ]
